name: unraid_ui
description: Unraid Mobile

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+12

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  graphql_flutter: ^5.1.2
  shared_preferences: ^2.5.3
  provider: ^6.1.2
  font_awesome_flutter: ^10.8.0
  package_info_plus: ^8.3.0
  flutter_launcher_icons: ^0.14.3
  connectivity_plus: ^6.1.3
  pub_semver: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/icon/ 

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21